url: https://filmbloggen.net
title: Filmbloggen
description: >
  I dont trust horses. Their shoes are
  permanent. Who makes that sort of
  commitment to a shoe?! – Arthur
theme: minima
paginate: 5
plugins: [jekyll-paginate]
google_analytics: UA-8420880-9
lang: no
